version: '3.8'

services:
  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: node main.js

# Express server configuration
server:
  framework: Express
  port: 3000
  routes:
    - path: /
      method: GET
      response:
        content_type: application/json
        message: "Hello guys!"
